version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: apartment-listing-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-apartment_listing}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - apartment-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  # NestJS Backend
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: apartment-listing-backend
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${BACKEND_PORT:-3001}
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-apartment_listing}?schema=public
      SKIP_SEED: ${SKIP_SEED:-false}
    ports:
      - '${BACKEND_PORT:-3001}:3001'
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./apps/backend:/app/apps/backend
      - ./packages/shared:/app/packages/shared
      - backend_node_modules:/app/node_modules
      - backend_app_node_modules:/app/apps/backend/node_modules
    networks:
      - apartment-network
    command: sh -c "npx prisma generate && npx prisma migrate deploy && ([ \"$SKIP_SEED\" = \"false\" ] && pnpm prisma:seed || echo 'Skipping seed...') && pnpm start:dev"

  # Next.js Frontend
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: apartment-listing-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      NEXT_PUBLIC_API_URL: http://localhost:${BACKEND_PORT:-3001}
    ports:
      - '${FRONTEND_PORT:-3000}:3000'
    depends_on:
      - backend
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - ./packages/shared:/app/packages/shared
      - frontend_node_modules:/app/node_modules
      - frontend_app_node_modules:/app/apps/frontend/node_modules
      - frontend_next:/app/apps/frontend/.next
    networks:
      - apartment-network
    command: pnpm dev

volumes:
  postgres_data:
    driver: local
  backend_node_modules:
    driver: local
  backend_app_node_modules:
    driver: local
  frontend_node_modules:
    driver: local
  frontend_app_node_modules:
    driver: local
  frontend_next:
    driver: local

networks:
  apartment-network:
    driver: bridge
